version: '2'
services:
  mariadb:
    image: mariadb:10.1
    command: mysqld --innodb-buffer-pool-size=64M
    volumes:
      - "./mariadb:/var/lib/mysql"
      # - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"
    restart: always
    env_file:
      - "./mariadb.env"
  pad:
    depends_on:
      - mariadb
    build: .
    links:
      - mariadb
    restart: always
    ports:
      - "42091:9001"
    restart: always
